

#ifndef __SC__CONFIG_H__
#define __SC__CONFIG_H__


#define SPEEDCC_FEATURE_ENABLE_MEMORY_POOL

#ifdef SPEEDCC_FEATURE_ENABLE_MEMORY_POOL
#define SPEEDCC_FEATURE_MEMORY_POOL_THREAD_SAFE
#endif

#endif // __SC__CONFIG_H__
